### ISSUE TITLE
A few ideas for writing maintainable CSS

### ISSUE THREAD

**Issue by stphndxn** [bufferapp/css-style-guide#2]
In yesterday's design sync, we spoke a lot about object-orientated design and it feels that this thinking could lead us to some ideas about how we might approach molecular design! This feels great to explore this kind of thinking on the CSS level, too!

A few rules of thumb that we might explore could be:
- Avoid writing DRY code, unless purely coincidental. Try and keep away from writing `@extend`s and `@mixins`, etc. to avoid making the unrelated related.
- single responsibility and open/close principles
- object-orientated
- separation of concerns

Keen to hear any thoughts on these and to kick-start the conversation! :smile:

**Comment by Alex-ray** [comment]
Great initiative @stevemdixon love where your going with this!

I sympathize with your thoughts around 'Avoiding writing DRY code for the sake of being DRY', I think this is one of those things that is easy to do with OO design and takes a lot of experience to get good at knowing when you should abstract something vs keep it specific. 

In my experience I have found writing Modular CSS quite a bit easier to work with and maintain than OO CSS. They both definitely have their strengths and weaknesses, but I have found modular CSS to describe things in a way that is more in line with how most people think about designing websites. 

In particular I have really loved the ideas around [Scalable and Modular Architecture for CSS](https://smacss.com/book) . 

I have also really enjoyed the style guides by [Google](https://google.github.io/styleguide/htmlcssguide.xml) and [Airbnb](https://github.com/airbnb/css)

I hope this gives you some good inspiration, love that you guys are having these conversations and would love to help in any way that I can :smile:

**Comment by stphndxn** [comment]
Thanks so much for this, @Alex-ray! :grinning: I love writing modular CSS and the Google and Airbnb style guides are awesome! A few ideas that also spring to mind is how we might lay out our properties, too!

**Alphabetical**

``` css
.declaration-order {
  bottom: 0;
  color: #333;
  display: block;
  float: right;
  font: normal 13px "Helvetica Neue", sans-serif;
  height: 100px;
  left: 0;
  line-height: 1.5;
  opacity: 1;
  position: absolute;
  right: 0;
  text-align: center;
  top: 0;
  width: 100px;
  z-index: 100;
}
```

verus

**Box Model**

``` css
.declaration-order {
  /* Positioning */
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 100;

  /* Box-model */
  display: block;
  float: right;
  width: 100px;
  height: 100px;

  /* Typography */
  font: normal 13px "Helvetica Neue", sans-serif;
  line-height: 1.5;
  color: #333;
  text-align: center;

  /* Visual */
  background-color: #f5f5f5;
  border: 1px solid #e5e5e5;
  border-radius: 3px;

  /* Misc */
  opacity: 1;
}
```
